import { StyleSheet, Text, View } from "react-native";

export default function ProfileIcon({ initials, size = 42 }: any) {
  return (
    <View
      // Code Generated by Sidekick is for learning and experimentation purposes only.
      style={[
        styles.container,
        { width: size, height: size, borderRadius: size / 2 },
      ]}
    >
      <Text style={[styles.text, { fontSize: 14 }]}>{initials}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: "#1c3b89",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  text: {
    color: "#fff",
    fontWeight: "medium",
  },
});
