import { Colors } from "@/constants/Colors";
import { Feather } from "@expo/vector-icons";
import React from "react";
import {
  FlatList,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

export default function RecentActivitySection({
  onCardPress,
  recentSearches,
}: any) {
  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerText}>Recent Activity</Text>
        <TouchableOpacity>
          <Feather
            name="arrow-right"
            size={20}
            color={Colors["dark"].foreground}
          />
        </TouchableOpacity>
      </View>
      <FlatList
        // Code Generated by Sidekick is for learning and experimentation purposes only.
        data={recentSearches.slice(0, 3)}
        keyExtractor={(item) => item.id}
        showsVerticalScrollIndicator={false}
        renderItem={({ item }) => (
          <TouchableOpacity
            style={styles.card}
            onPress={() => onCardPress && onCardPress(item)}
            activeOpacity={0.8}
          >
            <Text style={styles.title} numberOfLines={2}>
              {item.title}
            </Text>
            <Text style={styles.date}>{item.date}</Text>
          </TouchableOpacity>
        )}
        ItemSeparatorComponent={() => <View style={{ height: 12 }} />}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    marginBottom: 0,
    paddingHorizontal: 20,
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  headerText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  seeAll: {
    fontSize: 14,
    color: "#1db954",
    fontWeight: "bold",
  },
  card: {
    backgroundColor: Colors["dark"].cardColor,
    borderRadius: 8,
    borderColor: "#292929",
    borderWidth: 1,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
    elevation: 2,
    justifyContent: "space-between",
  },
  title: {
    fontSize: 15,
    color: "#fff",
    fontWeight: "500",
    marginBottom: 8,
  },
  date: {
    fontSize: 12,
    color: "#aaa",
  },
});
