import { Colors } from "@/constants/Colors";
import { Feather } from "@expo/vector-icons";
import React from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";

export default function WordOfTheDay({
  word,
  pronunciation,
  definition,
  example,
  date,
}: any) {
  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerText}>Word of the Day</Text>
        <TouchableOpacity>
          <Text style={styles.arrow}>
            {" "}
            <Feather
              name="arrow-right"
              size={20}
              color={Colors["dark"].foreground}
            />
          </Text>
        </TouchableOpacity>
      </View>
      <View style={styles.card}>
        <View style={styles.wordSection}>
          <Text style={styles.word}>{word}</Text>
          <TouchableOpacity>
            {/* <Image
              // Code Generated by Sidekick is for learning and experimentation purposes only.
              source={require("@/assets/icons/speaker.png")}
              style={styles.icon}
            /> */}
          </TouchableOpacity>
        </View>
        <Text style={styles.pronunciation}>{pronunciation}</Text>
        <Text style={styles.definition}>{definition}</Text>
        <Text style={styles.example}>{example}</Text>
        <View style={styles.dateContainer}>
          <Text style={styles.date}>{date}</Text>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    marginVertical: 20,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  headerText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  arrow: {
    fontSize: 18,
    color: "#fff",
  },
  card: {
    backgroundColor: Colors["dark"].cardColor,
    borderRadius: 10,
    borderColor: "#292929",
    borderWidth: 1,
    padding: 15,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 5,
    elevation: 3,
  },
  wordSection: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  word: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    flex: 1,
  },
  icon: {
    width: 24,
    height: 24,
    tintColor: "#fff",
  },
  pronunciation: {
    fontSize: 16,
    color: "#aaa",
    marginBottom: 10,
  },
  definition: {
    fontSize: 16,
    color: "#fff",
    marginBottom: 10,
  },
  example: {
    fontSize: 14,
    fontStyle: "italic",
    color: "#aaa",
    marginBottom: 10,
  },
  dateContainer: {
    alignSelf: "flex-end",
    backgroundColor: "#033d18fa",
    borderRadius: 5,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  date: {
    fontSize: 12,
    color: "#fff",
  },
});
