import BgContainer from "@/components/ui/BgContainer";
import { Colors } from "@/constants/Colors";
import React from "react";
import {
  FlatList,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

export default function history() {
  const recentSearches = [
    { id: "1", title: "Artificial Intelligence", date: "Mar 12, 2024" },
    { id: "2", title: "React Native Styling", date: "Mar 11, 2024" },
    { id: "3", title: "Expo vs Bare Workflow", date: "Mar 10, 2024" },
    { id: "4", title: "Glassmorphism UI", date: "Mar 9, 2024" },
    { id: "5", title: "AsyncStorage Best Practices", date: "Mar 8, 2024" },
    { id: "1", title: "Artificial Intelligence", date: "Mar 12, 2024" },
    { id: "2", title: "React Native Styling", date: "Mar 11, 2024" },
    { id: "3", title: "Expo vs Bare Workflow", date: "Mar 10, 2024" },
    { id: "4", title: "Glassmorphism UI", date: "Mar 9, 2024" },
    { id: "5", title: "AsyncStorage Best Practices", date: "Mar 8, 2024" },
    { id: "1", title: "Artificial Intelligence", date: "Mar 12, 2024" },
    { id: "2", title: "React Native Styling", date: "Mar 11, 2024" },
    { id: "3", title: "Expo vs Bare Workflow", date: "Mar 10, 2024" },
    { id: "4", title: "Glassmorphism UI", date: "Mar 9, 2024" },
    { id: "5", title: "AsyncStorage Best Practices", date: "Mar 8, 2024" },
  ];
  return (
    <BgContainer>
      <View style={styles.container}>
        <Text style={styles.headerText}>Recent Activity</Text>

        <FlatList
          // Code Generated by Sidekick is for learning and experimentation purposes only.
          data={recentSearches}
          keyExtractor={(item) => item.id}
          showsVerticalScrollIndicator={false}
          renderItem={({ item }) => (
            <TouchableOpacity
              style={styles.card}
              onPress={(item: any) => alert(item.title)}
              activeOpacity={0.8}
            >
              <Text style={styles.title} numberOfLines={2}>
                {item.title}
              </Text>
              <Text style={styles.date}>{item.date}</Text>
            </TouchableOpacity>
          )}
          ItemSeparatorComponent={() => <View style={{ height: 12 }} />}
        />
      </View>
    </BgContainer>
  );
}
const styles = StyleSheet.create({
  container: {
    marginBottom: 0,
    paddingHorizontal: 20,
    flex: 1,
  },

  headerText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 10,
  },
  seeAll: {
    fontSize: 14,
    color: "#1db954",
    fontWeight: "bold",
  },
  card: {
    backgroundColor: Colors["dark"].cardColor,
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
    elevation: 2,
    justifyContent: "space-between",
  },
  title: {
    fontSize: 15,
    color: "#fff",
    fontWeight: "500",
    marginBottom: 8,
  },
  date: {
    fontSize: 12,
    color: "#aaa",
  },
});
